/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cc86.MMC.client;

import javax.swing.JPanel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author tgoerner
 */
public class Menu extends javax.swing.JFrame
{

    private static final Logger l = LogManager.getLogger();
    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainTabs = new javax.swing.JTabbedPane();
        pGeneral = new javax.swing.JPanel();
        pDebug = new javax.swing.JPanel();
        btnIxxME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pGeneralLayout = new javax.swing.GroupLayout(pGeneral);
        pGeneral.setLayout(pGeneralLayout);
        pGeneralLayout.setHorizontalGroup(
            pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        pGeneralLayout.setVerticalGroup(
            pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        mainTabs.addTab("General", pGeneral);

        btnIxxME.setText("Server Ixxen");
        btnIxxME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIxxMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDebugLayout = new javax.swing.GroupLayout(pDebug);
        pDebug.setLayout(pDebugLayout);
        pDebugLayout.setHorizontalGroup(
            pDebugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDebugLayout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addComponent(btnIxxME)
                .addGap(24, 24, 24))
        );
        pDebugLayout.setVerticalGroup(
            pDebugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDebugLayout.createSequentialGroup()
                .addGap(0, 435, Short.MAX_VALUE)
                .addComponent(btnIxxME))
        );

        mainTabs.addTab("DevUtils", pDebug);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIxxMEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIxxMEActionPerformed
    {//GEN-HEADEREND:event_btnIxxMEActionPerformed
        Main.serverKillen();
    }//GEN-LAST:event_btnIxxMEActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private static Menu m = new Menu();;
    
    public static void bootUI()
    {
        m.setVisible(true);
        l.error("Ach LEgg mi doch am arsch");
        Main.getDispatcher().startUIs();
        //m.pGeneral.add()
    }

    public static Menu getMenu()
    {
        return m;
    }
    
    
    
    public void registerTab(String name, JPanel p)
    {
        mainTabs.add(name, p);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIxxME;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JPanel pDebug;
    private javax.swing.JPanel pGeneral;
    // End of variables declaration//GEN-END:variables
}
