/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cc86.MMC.client;

import java.awt.EventQueue;
import javax.swing.JPanel;
import org.cc86.MMC.client.API.Module;

/**
 *
 * @author tgoerner
 */
public class StreamUI extends JPanel
{

    /**
     * Creates new form StreamUI
     */
    public StreamUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        vnc = new javax.swing.JButton();
        mp4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMP4WithSound = new javax.swing.JButton();
        btnStopAll = new javax.swing.JButton();
        lblSource = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnDisconnect = new javax.swing.JButton();

        vnc.setText("VNC");
        vnc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vncActionPerformed(evt);
            }
        });

        mp4.setText("MP4");
        mp4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mp4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nur Video");

        jLabel2.setText("Video + Audio");

        btnMP4WithSound.setText("MP4(Hohe Latenz)");
        btnMP4WithSound.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMP4WithSoundActionPerformed(evt);
            }
        });

        btnStopAll.setText("Alle Streams stoppen");
        btnStopAll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStopAllActionPerformed(evt);
            }
        });

        lblSource.setText("Aktuelle Quelle:");

        lblStatus.setText("Status");

        btnDisconnect.setText("Stream beenden");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vnc, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnMP4WithSound)
                    .addComponent(btnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 151, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStopAll, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(lblSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mp4)
                    .addComponent(btnMP4WithSound))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vnc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStopAll)
                    .addComponent(btnDisconnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vncActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vncActionPerformed
    {//GEN-HEADEREND:event_vncActionPerformed
        Module[] m = Main.getDispatcher().getModules();
        for (Object m1 : m) {
            if(m1 instanceof Mod_Stream)
            {
                ((Mod_Stream)m1).streamVNC();
            }
        }
    }//GEN-LAST:event_vncActionPerformed

    private void mp4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mp4ActionPerformed
    {//GEN-HEADEREND:event_mp4ActionPerformed
        Module[] m = Main.getDispatcher().getModules();
        for (Object m1 : m) {
            if(m1 instanceof Mod_Stream)
            {
                ((Mod_Stream)m1).streamMP4(true);
            }
        }
    }//GEN-LAST:event_mp4ActionPerformed

    private void btnMP4WithSoundActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMP4WithSoundActionPerformed
    {//GEN-HEADEREND:event_btnMP4WithSoundActionPerformed
        Module[] m = Main.getDispatcher().getModules();
        for (Object m1 : m) {
            if(m1 instanceof Mod_Stream)
            {
                ((Mod_Stream)m1).streamMP4(false);
            }
        }
    }//GEN-LAST:event_btnMP4WithSoundActionPerformed

    private void btnStopAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStopAllActionPerformed
    {//GEN-HEADEREND:event_btnStopAllActionPerformed
        Module[] m = Main.getDispatcher().getModules();
        for (Object m1 : m) {
            if(m1 instanceof Mod_Stream)
            {
                ((Mod_Stream)m1).stopAllStreams();
            }
        }
    }//GEN-LAST:event_btnStopAllActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDisconnectActionPerformed
    {//GEN-HEADEREND:event_btnDisconnectActionPerformed
         Module[] m = Main.getDispatcher().getModules();
        for (Object m1 : m) {
            if(m1 instanceof Mod_Stream)
            {
                ((Mod_Stream)m1).stopThisStream();
            }
        }
    }//GEN-LAST:event_btnDisconnectActionPerformed

    public void updateStatus(final String msg)
    {
        EventQueue.invokeLater(()->lblStatus.setText("Status: "+msg));
    }
            
    public void updateSource(final String msg)
    {
        EventQueue.invokeLater(()->lblStatus.setText("Aktuelle Quelle: "+msg));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnMP4WithSound;
    private javax.swing.JButton btnStopAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JButton mp4;
    private javax.swing.JButton vnc;
    // End of variables declaration//GEN-END:variables
}
