/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cc86.MMC.client.jukebox;

import java.awt.EventQueue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.cc86.MMC.client.Mod_Jukebox;

/**
 *
 * @author tgoerner
 */
public class JukeBoxUI extends javax.swing.JPanel
{
    private static final Logger l = LogManager.getLogger();
    private Mod_Jukebox jbx;

    private HashMap<String,String> pool;
            
    
    /**
     * Creates new form JukeBoxUI
     * @param x instance of the underlying mod_jukebox classs
     */
    public JukeBoxUI(Mod_Jukebox x)
    {
        jbx=x;
        initComponents();
    }
    public void updatePool(HashMap<String,String> pooldata)
    {
        pool=pooldata;
        Set<String> pooltitles = pool.keySet();
        final List<String> poollist = Arrays.asList(pooltitles.toArray(new String[0]));
        EventQueue.invokeLater(()->{
            ((DefaultListModel)lstPool.getModel()).clear();
            poollist.forEach((s)->((DefaultListModel)lstPool.getModel()).addElement(s));
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPool = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnManageLocal = new javax.swing.JButton();
        btnEnqueue = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDetails = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstQUE = new javax.swing.JList();

        lstPool.setModel(new DefaultListModel<String>());
        lstPool.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstPool);

        jButton1.setText("Play");

        jButton2.setText("Skip");

        btnManageLocal.setText("Lokale Liste verwalten");

        btnEnqueue.setText("Einreihen");
        btnEnqueue.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnqueueActionPerformed(evt);
            }
        });

        txaDetails.setEditable(false);
        txaDetails.setColumns(20);
        txaDetails.setRows(5);
        txaDetails.setEnabled(false);
        jScrollPane2.setViewportView(txaDetails);

        lstQUE.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(lstQUE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnqueue)
                                    .addComponent(btnManageLocal))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnqueue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnqueueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnqueueActionPerformed
    {//GEN-HEADEREND:event_btnEnqueueActionPerformed
        String trackid = pool.get((String)lstPool.getSelectedValue());
        jbx.snedTrackPlaybackRequest(trackid, true);
    }//GEN-LAST:event_btnEnqueueActionPerformed

public void updateList(final List<String> elements)
{
    l.info("updateList()");
    EventQueue.invokeLater(()->{
        DefaultListModel mdl = (DefaultListModel) lstQUE.getModel();
        mdl.clear();
        
        if(elements==null||elements.isEmpty())
        {
            l.info("empty LST");
            return;
        }
          
        elements.forEach((s)->mdl.addElement(s));
    });
    
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnqueue;
    private javax.swing.JButton btnManageLocal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstPool;
    private javax.swing.JList lstQUE;
    private javax.swing.JTextArea txaDetails;
    // End of variables declaration//GEN-END:variables
}
