/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cc86.MMC.client.jukebox;

import de.nplusc.izc.tools.baseTools.Messagers;
import java.awt.EventQueue;
import java.io.File;
import java.util.Set;
import javax.swing.DefaultListModel;
import jnafilechooser.api.WindowsFileChooser;
import jnafilechooser.api.WindowsFolderBrowser;
import org.cc86.MMC.client.Menu;
import org.cc86.MMC.client.Mod_Jukebox;

/**
 *
 * @author tgoerner
 */
public class JukeBoxPoolManagment extends javax.swing.JPanel
{
    private final Mod_Jukebox jbx;
    /**
     * Creates new form JukeBoxPoolManagment
     * @param x instance of the underlying mod_jukebox classs
     */
    public JukeBoxPoolManagment(Mod_Jukebox x)
    {
        jbx=x;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnAddFolder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFolders = new javax.swing.JList();
        btnRmvFolder = new javax.swing.JButton();
        btnAddiZpl = new javax.swing.JButton();

        btnAddFolder.setText("Ordner hinzufügen");
        btnAddFolder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddFolderActionPerformed(evt);
            }
        });

        lstFolders.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(lstFolders);

        btnRmvFolder.setText("Element entfernen");

        btnAddiZpl.setText("m3u/iZpl Playliste hinzufügen");
        btnAddiZpl.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddiZplActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddiZpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddFolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRmvFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddFolder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddiZpl)
                .addGap(63, 63, 63)
                .addComponent(btnRmvFolder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFolderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddFolderActionPerformed
    {//GEN-HEADEREND:event_btnAddFolderActionPerformed
         new Thread(()->{
            File fldr = new WindowsFolderBrowser().showDialog(Menu.getMenu());
            //Messagers.SingleLineMsg(fldr.getAbsolutePath(),"DebugOut");
            if(fldr==null)
            {
                return;
            }
            jbx.getFileProvider().addDirectoryForScan(fldr.getAbsolutePath());
            resyncList();
        }).start();
    }//GEN-LAST:event_btnAddFolderActionPerformed

    private void btnAddiZplActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddiZplActionPerformed
    {//GEN-HEADEREND:event_btnAddiZplActionPerformed
        new Thread(()->{
            WindowsFileChooser wfc = new WindowsFileChooser();
            
            wfc.addFilter("Playlist Files", "m3u","izpl");
            
            if (!wfc.showOpenDialog(Menu.getMenu())) {
                return;
            }
            File plf = wfc.getSelectedFile();
             // do something with f
            
            //
            //Messagers.SingleLineMsg(plf.getAbsolutePath(),"DebugOut");
            jbx.getFileProvider().addDirectoryForScan(plf.getAbsolutePath());
            resyncList();
        }).start();
    }//GEN-LAST:event_btnAddiZplActionPerformed

    private void resyncList()
    {
        EventQueue.invokeLater(()->
        {
            Set<String> paths = jbx.getFileProvider().getPaths();
            DefaultListModel<String> lm = (DefaultListModel<String>) lstFolders.getModel();
            lm.clear();
            paths.forEach(lm::addElement);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFolder;
    private javax.swing.JButton btnAddiZpl;
    private javax.swing.JButton btnRmvFolder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstFolders;
    // End of variables declaration//GEN-END:variables
}
